[project]
name = "" # Project Name
includes = ["luzhelena"] # Example include

[defines]
basedatos = ""
basedatos_content = """
"""
user = "user_poo"
pass = "123456"
conexion_establecida = "\"conectado a mysql\""

[nbproject]

[[dao_entities]]
name = "Revista"
fields = [
    { accessor = "private", type = "Integer", name = "cod_revista" },
    { accessor = "private", type = "String", name = "nombre_revista" },
    { accessor = "private", type = "String", name = "categoria_revista" },
    { accessor = "private", type = "String", name = "issn_revista" }
]

[[dao_entities]]
name = "Articulo"
fields = [
    { accessor = "private", type = "Integer", name = "cod_articulo" },
    { accessor = "private", type = "String", name = "nombre_articulo" },
    { accessor = "private", type = "Short", name = "cantidad_vistas_articulo" },
    { accessor = "private", type = "Integer", name = "open_articulo" }
]
