from .config import getConfig
from .argument import Argument

class Method:
    template = """{annotations}{t}{accessor} {return_type}{name}({arguments}) {{
{body}{t}}}
"""

    def __init__(self, method):
        self.accessor = getConfig(method, 'accessor')
        self.return_type = getConfig(method, 'return_type', True)
        self.annotations = getConfig(method, 'annotations', True)
        self.name = getConfig(method, 'name')
        self.arguments = Argument.fromArguments(getConfig(method, 'arguments', True))
        self.body = getConfig(method, 'body', True)
        self.is_constructor = getConfig(method, 'is_constructor', True)

    def fromMethods(methods):
        objs = []

        if methods:
            for method in methods:
                objs.append(Method(method))

        return objs
    
    def genAnnotations(self, t):
        self.gen_annotations = ''

        if self.annotations:
            for annotation in self.annotations:
                gen_annotation = t + '@' + annotation

                if not self.gen_annotations == '':
                    self.gen_annotations = '\n'.join([self.gen_annotations, gen_annotation])
                else:
                    self.gen_annotations = gen_annotation + '\n'
            

    def genArguments(self):
        self.gen_arguments = ''

        if self.arguments:
            for argument in self.arguments:
                if not self.gen_arguments == '':
                    self.gen_arguments = ','.join([self.gen_arguments, argument.generate()])
                else:
                    self.gen_arguments = argument.generate()

    def genBody(self, t):
        self.gen_body = ''

        if self.body:
            for line in self.body.split('\n'):
                self.gen_body += f'{t}    {line}\n'

    def generate(self, t):
        if not self.return_type and not self.is_constructor:
            self.return_type = 'void '
        elif not self.is_constructor:
            self.return_type += ' '
        else:
            self.return_type = ''
        
        if not self.body and not self.body == '':
            self.body = 'throw new java.lang.UnsupportedOperationException("Autogenerated Method!");'

        self.genAnnotations(t)
        self.genArguments()
        self.genBody(t)

        return self.template.format(t=t, accessor=self.accessor, return_type=self.return_type, annotations=self.gen_annotations, name=self.name, arguments=self.gen_arguments, body=self.gen_body)
