[project]
includes = ["netbeans"]
packages = [
    "edu.usta.configuracion",
    "edu.usta.daos",
    "edu.usta.entidades",
    "edu.usta.formularios",
    "edu.usta.iconos",
    "edu.usta.interfaces"
]

[[project.custom_handlers]]
name = "Daos y Entidades"
key = "entidades"
handler = "dao_entidades"

[[files]]
folder = "misLibrerias"
name = "mariadb-java-client.jar"
origin = "$luzhelena"

[[files]]
folder = "misLibrerias"
name = "flatlaf-3.2.jar"
origin = "$luzhelena"

[[files]]
folder = "miBasedatos"
name = "%basedatos%_ddl.sql"
create = true
content = "%basedatos_content%"

[[classes]]
package = "edu.usta.configuracion"
name = "MiConexion"
origin = "$luzhelena"

[[classes]]
package = "edu.usta.interfaces"
name = "Funcionalidad"
origin = "$luzhelena"
